name: Generate OCI artifacts

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      startArtifactVersion:
        description: Starting with Business Central Version
        required: false
        default: ''

jobs:
  GetBcVersions:
    runs-on: [ windows-latest ]
    outputs:
      versionMatrixJson: ${{ steps.GetVersions.outputs.versionMatrixJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GetVersions
        shell: pwsh
        id: GetVersions
        env:
          startArtifactVersion: ${{ github.event.inputs.startArtifactVersion }}
        run: |
          . (Join-Path $env:GITHUB_WORKSPACE "GetVersions.ps1")

  GenerateOciArtifacts:
    needs: GetBcVersions
    runs-on: [ windows-latest ]
    strategy: ${{ fromJson(needs.GetBcVersions.outputs.versionMatrixJson) }}
    name: ${{ matrix.type }}-${{ matrix.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GenerateOciArtifacts
        shell: pwsh
        env:
          type: ${{ matrix.type }}
          version: ${{ matrix.version }}
          registryPassword: ${{ secrets.REGISTRYPASSWORD}}
        run: |
          . (Join-Path $env:GITHUB_WORKSPACE "GenerateOciArtifacts.ps1")
