name: Generate OCI artifacts

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      startArtifactVersion:
        description: Starting with Business Central Version
        required: false
        default: ''

jobs:
  GenerateSandboxPlatFormOciArtifacts:
    runs-on: [ windows-latest ]
    name: Sandbox-Platform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: UpdateOciArtifacts
        shell: pwsh
        env:
          type: sandbox
          country: platform
          startArtifactVersion: ${{ github.event.inputs.startArtifactVersion }}
          registryPassword: ${{ secrets.REGISTRYPASSWORD}}
        run: |
          . (Join-Path $env:GITHUB_WORKSPACE "UpdateOciArtifacts.ps1")

  GenerateSandboxOciArtifacts:
    needs: GenerateSandboxPlatFormOciArtifacts
    runs-on: [ windows-latest ]
    strategy:
      matrix:
        country: [ "w1" ]
      fail-fast: false
    name: Sandbox-${{ matrix.country }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: UpdateOciArtifacts
        shell: pwsh
        env:
          type: sandbox
          country: ${{ matrix.country }}
          startArtifactVersion: ${{ github.event.inputs.startArtifactVersion }}
          registryPassword: ${{ secrets.REGISTRYPASSWORD}}
        run: |
          . (Join-Path $env:GITHUB_WORKSPACE "UpdateOciArtifacts.ps1")

  GenerateOnpremPlatFormOciArtifacts:
    runs-on: [ windows-latest ]
    name: Sandbox-Platform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: UpdateOciArtifacts
        shell: pwsh
        env:
          type: onprem
          country: platform
          startArtifactVersion: ${{ github.event.inputs.startArtifactVersion }}
          registryPassword: ${{ secrets.REGISTRYPASSWORD}}
        run: |
          . (Join-Path $env:GITHUB_WORKSPACE "UpdateOciArtifacts.ps1")

  GenerateOnpremOciArtifacts:
    needs: GenerateOnpremPlatFormOciArtifacts
    runs-on: [ windows-latest ]
    strategy:
      matrix:
        country: [ "w1" ]
      fail-fast: false
    name: Onprem-${{ matrix.country }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: UpdateOciArtifacts
        shell: pwsh
        env:
          type: onprem
          country: ${{ matrix.country }}
          startArtifactVersion: ${{ github.event.inputs.startArtifactVersion }}
          registryPassword: ${{ secrets.REGISTRYPASSWORD}}
        run: |
          . (Join-Path $env:GITHUB_WORKSPACE "UpdateOciArtifacts.ps1")
